### ISSUE TITLE
Définir format des pages markdown

### ISSUE THREAD

**Issue by PaulReeve717** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#21]
Il faut définir le format que devrons prendre les pages markdown saisies par l'utilisateur.
Il faudrait entre autre un symbole de séparation entre métadonnées et données utilisateur afin que le seul ces dernières soient converties en HTML

**Comment by arbroween** [comment]
Estimation
- Min : 30min
- Max : 2h
- Espéré : 1h

**Comment by arbroween** [comment]
J'ai passé 2h dessus pour le moment

**Comment by arbroween** [comment]
Le format du Markdown supporté est celui de l'exemple dans le cahier des charges
