### ISSUE TITLE
Affichage de la version

### ISSUE THREAD

**Issue by arbroween** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#22]
Afficher la version du logiciel lorsque celui-ci est appelé avec l'option `-version`.

temps estimé : 
optimiste : 30min
pessimiste : 2h
attendu : 1h

temps passé : 1h10

**Comment by soso24soso** [comment]
l'implémentation actuelle de la version risque de ne pas marcher une fois compilé en .jar
