### ISSUE TITLE
Initialiser un site statique (init)

### ISSUE THREAD

**Issue by arbroween** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#25]
Pouvoir créer un nouveau site statique à l'aide de la sous-commande `init chemin/vers/dossier`.

Le nouveau site généré contient à sa racine:
- un fichier `config.json` avec une configuration initiale
- un fichier `index.md` initial correspondant à la page d'accueil

- [x] Parser l'argument                   | durée estimée : ws : 1h, mc : 30m, bc : 15min
- [x] Créer les dossiers                   | durée estimée : ws : 45m, mc : 30m, 15min
- [x]  Créer le fichier config.json    | durée estimée : ws : 30m, mc : 20m, 15min
- [x] Créer le fichier index.md        | durée estimée : ws : 30m, mc : 20min, 15min

**Comment by Klab93** [comment]
- [ ] Parser l'argument                   | durée estimée : ws : 1h, mc : 30m, bc : 15min
- [ ] Créer les dossiers                   | durée estimée : ws : 45m, mc : 30m, 15min
- [ ]  Créer le fichier config.json    | durée estimée : ws : 30m, mc : 20m, 15min
- [ ] Créer le fichier index.md        | durée estimée : ws : 30m, mc : 20min, 15min

**Comment by Klab93** [comment]
Choix : 
- La commande nécessite le paramètre
- Si le dossier entré n'existe pas : création des dossiers
- Une base de configuration est écrite dans les fichiers : index.md, config.json
- Utilisation des librairies IO
