### ISSUE TITLE
Publier release v0.0.1

### ISSUE THREAD

**Issue by arbroween** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#31]
- [x] Créer un tag git (v0.0.1) contenant la version finale du sprint 1
- [x] Créer une release téléchargeable depuis l'onglet Release

**Comment by Klab93** [comment]
Je vais chercher pour modifier le POM.xml

**Comment by arbroween** [comment]
La release v0.0.1 est disponible ! 🎉🎉🎉
