### ISSUE TITLE
Choix d'un moteur de template HTML

### ISSUE THREAD

**Issue by PaulReeve717** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#43]
Il faut choisir un moteur de template afin de pouvoir faire des insertions dans les fichiers HTML du site

(+) : 1h
(~): 1h30
(-): 2h

Temps passé: 1h15

**Comment by arbroween** [comment]
Une bibliothèque Java supportant la syntaxe Handlebar : https://github.com/jknack/handlebars.java

**Comment by arbroween** [comment]
Plusieurs bibliothèques Java avec des syntaxes différentes : 
- https://freemarker.apache.org/
- https://www.thymeleaf.org/
- http://velocity.apache.org/engine/1.7/user-guide.html#hello-velocity-world

**Comment by arbroween** [comment]
Une autre bibliothèque supportant la syntaxe Handlebar : https://github.com/samskivert/jmustache

**Comment by arbroween** [comment]
Une bibliothèque Java qui supporte la syntaxe Jade/Pug : 
- https://github.com/neuland/pug4j
