### ISSUE TITLE
Code benchmarking

### ISSUE THREAD

**Issue by arbroween** [gen-classroom/projet-bard_bourcoud_ganguillet_reeve#71]
- [x]  Mesurer les performances du compilateur markdown ou moteur de rendu avec JHM.

- [x] Profiler une exécution de la commande build avec VisualVM.
- [ ] Inclure les données dans le rapport et discuter d'une optimisation (sans nécessairement l'implémenter)

**Comment by Klab93** [comment]
Temps estimé:
(+) : 2h
(~): 3h
(-) : 4h
